### ISSUE TITLE
Error  arrnorm.py", line 49 

### ISSUE THREAD

**Issue by BoonlueKac** [SMByC/ArrNorm-Qgis-processing#3]
We got this massage 

Traceback (most recent call last):
File "C:\Users/Windows 10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ArrNorm\ArrNorm_algorithm.py", line 196, in processAlgorithm
arrnorm = Normalization(
File "C:\Users/Windows 10/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ArrNorm\core\arrnorm.py", line 49, in __init__
ref_dtype = gdal.Open(self.img_ref, GA_ReadOnly).GetRasterBand(1).DataType
TypeError: in method 'Band_DataType_get', argument 1 of type 'GDALRasterBandShadow *

Do you have any suggestion ?

**Comment by XavierCLL** [comment]
Hi @BoonlueKac 

That issue seems a problem with the reference data, most specifically the data type in the band 1 or the format, is it a tif image? check the data first.

**Comment by BoonlueKac** [comment]
I moved to use in Anaconda. It was successful and worked well. 
Thank you so much.

**Comment by BoonlueKac** [comment]
![Uploading test_pip.jpg…]()

**Comment by BoonlueKac** [comment]
![test_pip](https://github.com/SMByC/ArrNorm-Qgis-processing/assets/161188135/32da3bca-836c-4907-9888-5ca66acc4178)

**Comment by XavierCLL** [comment]
@BoonlueKac glad to hear that! I'm closing this issue for now.
